using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApi.Entities
{
    public class pay_elements
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
		public string account_code { get; set; }
        public string account_title { get; set; }
        public bool? is_active { get; set; }
        public string display { get; set; }
        public int? company_id { get; set; }
        public float? constant_value { get; set; }
        public int? currency_id { get; set; }
        public int? day_type_id { get; set; }
        public bool? is_deduct_absences { get; set; }
        public bool? is_deduct_midbreak { get; set; }
        public bool? is_deduct_tardy { get; set; }
        public bool? is_deduct_undertime { get; set; }
        public int? de_minimis_id { get; set; }
        public string display_order { get; set; }
        public float? divisor { get; set; }
        public bool? is_exclude_leave { get; set; }
        public bool? is_exclude_ob { get; set; }
        public float? expanded_tax_rate { get; set; }
        public float? fb_taxable_rate { get; set; }
        public bool? is_formula_for_all_employees { get; set; }
        public string group_code { get; set; }
        public string hdmf_loan_diskette_code { get; set; }
        public string hdmf_loan_excel_code { get; set; }
        public string hdmf_loan_printout_code { get; set; }
        public int? hour_type_id { get; set; }
        public bool? is_ignore_attendance { get; set; }
        public bool? is_include_basic { get; set; }
        public bool? is_include_13th_month { get; set; }
        public bool? is_include_in_hdmf { get; set; }
        public bool? is_include_in_net_pay { get; set; }
        public bool? is_include_in_phic { get; set; }
        public bool? is_include_in_sss { get; set; }
        public bool? is_include_nd { get; set; }
        public bool? is_include_ndot { get; set; }
        public bool? is_include_ot { get; set; }
        public int? interest_pay_element_id { get; set; }
        public float? interest_rate { get; set; }
        public int? interest_rate_type_id { get; set; }
        public int? interest_type_id { get; set; }
        public bool? is_13th_month_pay { get; set; }
        public bool? is_absent { get; set; }
        public bool? is_absent_al { get; set; }
        public bool? is_allowance { get; set; }
        public bool? is_cap_excess_credit_to_next_payroll { get; set; }
        public bool? is_company_loan { get; set; }
        public bool? is_compute_capping_for_loan { get; set; }
        public bool? is_compute_formula_after_net_pay { get; set; }
        public bool? is_deduct_halfday { get; set; }
        public bool? is_deduct_leave_hours { get; set; }
        public bool? is_deduct_unpaid_holiday { get; set; }
        public bool? is_de_minimis_benefits { get; set; }
        public bool? is_display_zero_value { get; set; }
        public bool? is_earning { get; set; }
        public bool? is_ew_tax { get; set; }
        public bool? is_ew_taxable { get; set; }
        public bool? is_fb_tax { get; set; }
        public bool? is_fb_taxable { get; set; }
        public bool? is_final_tax { get; set; }
        public bool? is_gross_up { get; set; }
        public bool? is_hdmf { get; set; }
        public bool? is_include_midbreak { get; set; }
        public bool? is_include_tardy { get; set; }
        public bool? is_include_undertime { get; set; }
        public bool? is_loan { get; set; }
        public bool? is_major_deduction { get; set; }
        public bool? is_midbreak { get; set; }
        public bool? is_midbreak_al { get; set; }
        public bool? is_minimum { get; set; }
        public bool? is_nd { get; set; }
        public bool? is_non_taxable_contributions { get; set; }
        public bool? is_non_taxable_salaries { get; set; }
        public bool? is_overtime { get; set; }
        public bool? is_phic { get; set; }
        public bool? is_premium_paid { get; set; }
        public bool? is_prorated { get; set; }
        public bool? is_reg_basic { get; set; }
        public bool? is_reg_basic_al { get; set; }
        public bool? is_reimbursement { get; set; }
        public bool? is_show_on_schedule_element_updates { get; set; }
        public bool? is_sss { get; set; }
        public bool? is_sss_ec { get; set; }
        public bool? is_tardy { get; set; }
        public bool? is_tardy_al { get; set; }
        public bool? is_taxable { get; set; }
        public bool? is_taxable_basic_salary { get; set; }
        public bool? is_taxable_commission { get; set; }
        public bool? is_taxable_ecola { get; set; }
        public bool? is_taxable_fees { get; set; }
        public bool? is_taxable_fixed_housing_allowance { get; set; }
        public bool? is_taxable_hazard_pay { get; set; }
        public bool? is_taxable_holiday_pay { get; set; }
        public bool? is_taxable_night_shift_differential { get; set; }
        public bool? is_taxable_other_regular1 { get; set; }
        public bool? is_taxable_other_regular2 { get; set; }
        public bool? is_taxable_other_supplementary1 { get; set; }
        public bool? is_taxable_other_supplementary2 { get; set; }
        public bool? is_taxable_overtime_pay { get; set; }
        public bool? is_taxable_profit_sharing { get; set; }
        public bool? is_taxable_representation { get; set; }
        public bool? is_taxable_transportation { get; set; }
        public bool? is_tax_paid_by_employer { get; set; }
        public bool? is_undertime { get; set; }
        public bool? is_undertime_al { get; set; }
        public bool? is_union { get; set; }
        public bool? is_wtax { get; set; }
        public int? loan_capping_amount_type_id { get; set; }
        public float? loan_capping_value { get; set; }
        public float? minimum_qty { get; set; }
        public int? mult { get; set; }
        public string name { get; set; }
        public int? no_of_payments { get; set; }
        public int? parent_pay_element_id { get; set; }
        public string payable_account_code { get; set; }
        public string pay_code { get; set; }
        public int? pay_element_display_id { get; set; }
        public int? pay_element_payroll_register_display_id { get; set; }
        public int? pay_element_type_id { get; set; }
        public string pay_reg_code { get; set; }
        public int? payroll_hour_type_id { get; set; }
        public string payroll_register_group_code { get; set; }
        public int? pay_tax_type_id { get; set; }
        public int? period_pay_element_id { get; set; }
        public int? priority_level { get; set; }
        public int? prorated_date_basis_id { get; set; }
        public int? rate_id { get; set; }
        public string sys_code { get; set; }
        public int? taxable_mult { get; set; }
        public int? time_type_id { get; set; }
        public int? time_unit_id { get; set; }
        public bool? is_use_formula { get; set; }
        public int? created_by_id { get; set; }
		public DateTime? date_created { get; set; }
		public int? modified_by_id { get; set; }
		public DateTime? date_modified { get; set; }

    }
}
